import Container from '@mui/material/Container';
import type { NextPage } from 'next';
import Head from 'next/head';
import Login from './Login';
import NovoCadastro from './NovoCadastro';

const Home: NextPage = () => {
  return (
    <Container
      sx={{
        width: "100%",
        height: "100%"
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NovoCadastro />
    </Container>
  );
}

export default Home;
